export const BLOCKS = [
  ['grass','Pasto','#58a93b'],['dirt','Tierra','#8a5933'],['stone','Piedra','#7c848b'],['cobble','Adoquín','#747b80'],
  ['sand','Arena','#decf83'],['gravel','Grava','#8f8b87'],['oak','Tronco','#9a6839'],['planks','Tablones','#b9854c'],
  ['leaves','Hojas','#347f3b'],['glass','Vidrio','#c7eef5'],['brick','Ladrillos','#a85040'],['coal','Carbón','#25282b'],
  ['iron','Hierro','#d6b9a1'],['gold','Oro','#f4d13e'],['redstone','Redstone','#d94039'],['diamond','Diamante','#4fe3da'],
  ['emerald','Esmeralda','#37cf69'],['obsidian','Obsidiana','#2d2440'],['snow','Nieve','#edf5f7'],['ice','Hielo','#a8e1f4'],
  ['clay','Arcilla','#9ba7ae'],['netherrack','Roca roja','#833c3c'],['glow','Piedra luminosa','#d5ad63'],['quartz','Cuarzo','#e8e2da'],
  ['blackstone','Piedra negra','#323238'],['deepslate','Pizarra profunda','#45484b'],['copper','Cobre','#c97a55'],['woolWhite','Lana blanca','#e6e6e2'],
  ['woolRed','Lana roja','#aa3f46'],['woolBlue','Lana azul','#3e5fa8'],['bookshelf','Librería','#8c6038'],['crafting','Mesa de crafteo','#9b6c39'],
  ['furnace','Horno','#73797d'],['chest','Cofre','#9a6a36'],['lamp','Lámpara','#d8a448'],['terracotta','Terracota','#a75f43'],['prismarine','Prismarina','#5b9f96'],
  ['endstone','Piedra pálida','#d9d89a'],['mud','Barro','#5f5148'],['moss','Musgo','#4e7d3b'],['redSand','Arena roja','#c87943'],
  ['basalt','Basalto','#4a4a50'],['calcite','Calcita','#e1ddd1'],['amethyst','Amatista','#936cc4'],['mushroom','Bloque hongo','#a95550'],
  ['darkPlanks','Madera oscura','#66503a'],['bamboo','Bambú','#a8bd52'],['seaLantern','Linterna marina','#b9e3dc'],['packedIce','Hielo compacto','#77b9d6'],
  ['bone','Bloque hueso','#dfd7bd'],['slime','Bloque gel','#74c85d'],['honey','Bloque miel','#d9952c'],['copperOx','Cobre oxidado','#4f9b85'],
  ['powerDust','Polvo conductor','#b32626'],['lever','Palanca','#786451'],['powerLamp','Lámpara eléctrica','#6f5b2a'],['portalStone','Piedra de portal','#312040'],['portalCore','Núcleo de portal','#7b36c9'],
  ['fossilRock','Roca fósil','#8a806f'],['dnaAnalyzer','Analizador de ADN','#6c8994'],['incubator','Incubadora','#a8d9cd'],['dinoCrate','Caja paleontológica','#89663f'],
  // V14 · defensa, ciencia y exploración
  ['electricFence','Cerca eléctrica','#6f8792'],['reinforcedWall','Muro reforzado','#4f5963'],['radarArray','Radar Mini-IA','#3f7286'],['bioScanner','Escáner biológico','#54a88e'],
  ['antiZombieGlass','Cristal antizombies','#9ed7dc'],['steelPlate','Placa de acero','#697780'],['hazardStripe','Bloque de seguridad','#d6a52b'],['scannerLight','Luz de escáner','#62d9c9'],
  ['fossilBrick','Ladrillo fósil','#a29478'],['medicalStation','Estación médica','#d9e4e7'],['ammoCrate','Caja de suministros','#586447'],['watchBeacon','Baliza de vigilancia','#d96c42'],
  // Nuevos bloques funcionales y de templos
  ['tnt','Dinamita TNT','#db372c'],['enchantTable','Mesa de encantamientos','#6b2d5c'],['magma','Bloque de magma','#a8411b'],['bedrock','Roca madre','#181818'],
].map(([id,name,sw],index)=>({id,name,sw,index,crafting:id==='crafting'}))

export const BLOCK_INDEX = Object.fromEntries(BLOCKS.map(b=>[b.id,b.index]))

export const BIOMES = [
  {id:'plains',name:'Pradera',color:'#71b84b',top:'grass',sub:'dirt',tree:0.018},
  {id:'forest',name:'Bosque',color:'#3d843f',top:'grass',sub:'dirt',tree:0.07},
  {id:'desert',name:'Desierto',color:'#dfca73',top:'sand',sub:'sand',tree:0},
  {id:'snow',name:'Tundra',color:'#e8f1f3',top:'snow',sub:'dirt',tree:0.025},
  {id:'taiga',name:'Taiga',color:'#527b63',top:'grass',sub:'dirt',tree:0.065},
  {id:'savanna',name:'Sabana',color:'#a6b64c',top:'grass',sub:'dirt',tree:0.022},
  {id:'swamp',name:'Pantano',color:'#536e45',top:'mud',sub:'clay',tree:0.045},
  {id:'jungle',name:'Selva',color:'#2e9148',top:'grass',sub:'dirt',tree:0.095},
  {id:'badlands',name:'Meseta roja',color:'#bc6c42',top:'redSand',sub:'terracotta',tree:0},
  {id:'mountains',name:'Montañas',color:'#7a8081',top:'stone',sub:'stone',tree:0.012},
  {id:'mushroom',name:'Islas de hongos',color:'#9b5674',top:'moss',sub:'dirt',tree:0.04},
  {id:'beach',name:'Playa',color:'#e3d58b',top:'sand',sub:'sand',tree:0},
]

export const TOOLS = [
  ['Mano','✋',1],['Pico de madera','⛏️',2],['Pico de piedra','⛏️',3],['Pico de hierro','⛏️',4],['Pico de oro','⛏️',4],['Pico de diamante','⛏️',5],
  ['Hacha de madera','🪓',2],['Hacha de piedra','🪓',3],['Hacha de hierro','🪓',4],['Hacha de diamante','🪓',5],
  ['Pala de madera','◢',2],['Pala de hierro','◢',4],['Pala de diamante','◢',5],['Espada de hierro','⚔️',3],['Espada de diamante','⚔️',5],
  ['Arco','🏹',4],['Ballesta','➶',5],['Tridente','🔱',6],['Tijeras','✂️',2],['Caña de pescar','🎣',1],['Escudo','🛡️',1],
  ['Chisquero de pedernal','🔥',2],['Pico encantado','✨⛏️',7],['Espada de fuego','🔥⚔️',7],['Peto de hierro','🛡️',3],['Peto de diamante','💎🛡️',6],
  // Jurassic World Reborn Tools
  ['Rifle tranquilizante','🔫',5],['Rastreador jurásico','📟',2],
  // Marvel Zombies Add-on Gear
  ['Martillo Mjolnir','🔨⚡',8],['Arco explosivo de Hawkeye','🏹💥',6],['Guantelete repulsor','🥊✨',6],['Traje Simbionte Spider-Man','🕷️🖤',9],
  // V14 · herramientas de ingeniería, defensa y paleontología
  ['Llave de ingeniería','🔧',3],['Escáner portátil','📡',2],['Bastón eléctrico','⚡',5],['Brocha paleontológica','🖌️',2],['Pico reforzado','⛏️',6],['Martillo de rescate','🔨',5]
].map(([name,icon,power])=>({name,icon,power,damage:name.includes('Espada')||name==='Tridente'||name==='Arco'||name==='Ballesta'||name==='Bastón eléctrico'||name==='Martillo de rescate'||name.includes('fuego')||name.includes('Mjolnir')||name.includes('Hawkeye')||name.includes('repulsor')||name.includes('Rifle')||name.includes('Simbionte')?power:1}))

export const MOB_TYPES = [
  {id:'cow',name:'Bovino',body:0x6e4a37,head:0x8a624b,kind:'passive',speed:.72,hp:10},
  {id:'pig',name:'Cerdito',body:0xe58e99,head:0xf3a7ae,kind:'passive',speed:.72,hp:10},
  {id:'sheep',name:'Oveja',body:0xe8e6dc,head:0x8f8b83,kind:'passive',speed:.7,hp:8},
  {id:'chicken',name:'Ave',body:0xf1f1e7,head:0xffffff,kind:'passive',speed:.85,hp:5},
  {id:'rabbit',name:'Conejo',body:0x9b8066,head:0xb69a7c,kind:'passive',speed:1.1,hp:4},
  {id:'wolf',name:'Lobo',body:0x9c9b91,head:0xb9b8ad,kind:'neutral',speed:1.15,hp:12},
  {id:'fox',name:'Zorro',body:0xc87232,head:0xe18b46,kind:'passive',speed:1.2,hp:8},
  {id:'bee',name:'Abeja',body:0xd9ad35,head:0xe9c857,kind:'neutral',speed:1.1,hp:6,flying:true},
  {id:'frog',name:'Rana',body:0x79a94b,head:0x8fc65a,kind:'passive',speed:.75,hp:6},
  {id:'camel',name:'Camello',body:0xc59b68,head:0xd3ad7e,kind:'passive',speed:.65,hp:16},
  {id:'goat',name:'Cabra',body:0xc7c0ad,head:0xe0d8c2,kind:'neutral',speed:1.0,hp:10},
  {id:'panda',name:'Panda',body:0xe7e4dc,head:0xd9d5ca,kind:'passive',speed:.55,hp:14},
  {id:'zombie',name:'Caminante verde',body:0x4e7b45,head:0x6a9e58,kind:'hostile',speed:1.0,hp:12},
  {id:'skeleton',name:'Arquero huesudo',body:0xd6d4ca,head:0xe8e5da,kind:'hostile',speed:.95,hp:10},
  {id:'creeper',name:'Explosivo verde',body:0x49a84d,head:0x55b958,kind:'hostile',speed:.9,hp:10},
  {id:'spider',name:'Araña nocturna',body:0x33292a,head:0x4a3538,kind:'hostile',speed:1.25,hp:10,wide:true},
  {id:'slime',name:'Gel saltarín',body:0x75c660,head:0x86d474,kind:'hostile',speed:.65,hp:8},
  {id:'witch',name:'Hechicera',body:0x5d4b67,head:0x8c746d,kind:'hostile',speed:.72,hp:14},
  {id:'enderman',name:'Caminante alto',body:0x1d1720,head:0x2b2030,kind:'neutral',speed:1.35,hp:18,tall:true},
  {id:'guardian',name:'Guardián marino',body:0x6d9c8f,head:0x86b2a4,kind:'hostile',speed:.85,hp:14,flying:true},
  {id:'blaze',name:'Espíritu de fuego',body:0xd58d2f,head:0xe9aa43,kind:'hostile',speed:1.0,hp:12,flying:true},
  {id:'phantom',name:'Planeador nocturno',body:0x475879,head:0x5a6e94,kind:'hostile',speed:1.4,hp:10,flying:true},
  {id:'villager',name:'Aldeano',body:0x805b45,head:0xc18b68,kind:'villager',speed:.62,hp:16},
  {id:'golem',name:'Guardián del pueblo',body:0xc5c0b5,head:0xd9d4c8,kind:'guardian',speed:.55,hp:30,tall:true},
  {id:'trader',name:'Comerciante viajero',body:0x416a8b,head:0xc18b68,kind:'villager',speed:.68,hp:16},
  // V15 · NPCs inteligentes y especializados
  {id:'npcBuilder',name:'Maestro constructor',body:0x8a6848,head:0xc7926f,kind:'villager',speed:.64,hp:20,npc:true,defaultRole:'constructor'},
  {id:'npcEngineer',name:'Ingeniera de sistemas',body:0x3f6672,head:0xc7926f,kind:'villager',speed:.68,hp:20,npc:true,defaultRole:'ingeniero'},
  {id:'npcMedic',name:'Médica de campo',body:0xe8ece8,head:0xc7926f,kind:'villager',speed:.72,hp:20,npc:true,defaultRole:'medico'},
  {id:'npcScientist',name:'Científica genética',body:0xd7e5e8,head:0xc7926f,kind:'villager',speed:.66,hp:18,npc:true,defaultRole:'cientifico'},
  {id:'npcPaleo',name:'Paleontólogo',body:0xb58b55,head:0xc7926f,kind:'villager',speed:.68,hp:18,npc:true,defaultRole:'paleontologo'},
  {id:'npcRanger',name:'Exploradora',body:0x476b45,head:0xc7926f,kind:'villager',speed:.82,hp:20,npc:true,defaultRole:'explorador'},
  {id:'npcSurvivor',name:'Superviviente',body:0x59616a,head:0xb98262,kind:'villager',speed:.84,hp:24,npc:true,defaultRole:'superviviente'},
  {id:'npcGuard',name:'Centinela',body:0x374b61,head:0xb98262,kind:'villager',speed:.90,hp:28,npc:true,defaultRole:'guardia'},
  {id:'llama',name:'Llama',body:0xc9b18e,head:0xdfc9aa,kind:'passive',speed:.65,hp:14},
  {id:'cat',name:'Gato',body:0x806b57,head:0x9b836c,kind:'passive',speed:1.05,hp:6},
  {id:'horse',name:'Caballo',body:0x7c573c,head:0x8e674a,kind:'passive',speed:1.4,hp:18},
  {id:'drowned',name:'Ahogado',body:0x487c75,head:0x5d9990,kind:'hostile',speed:.8,hp:12},
  {id:'snowGolem',name:'Guardián de nieve',body:0xf1f2ed,head:0xd88235,kind:'guardian',speed:.5,hp:12,tall:true},
  
  // Jurassic World Reborn Dinosaurs
  {id:'dinoRaptor',name:'Raptor plumado',body:0x577b55,head:0x6f9669,kind:'dinosaur',speed:1.65,hp:22,dinosaur:true,carnivore:true},
  {id:'dinoRex',name:'Gran tirano T-Rex',body:0x756343,head:0x8c7650,kind:'dinosaur',speed:1.1,hp:55,dinosaur:true,carnivore:true,tall:true},
  {id:'dinoTrike',name:'Trescuernos Triceratops',body:0x79866a,head:0x929d7f,kind:'dinosaur',speed:.75,hp:38,dinosaur:true,herbivore:true,wide:true},
  {id:'dinoLongneck',name:'Cuellolargo Braquiosaurio',body:0x697e74,head:0x80978c,kind:'dinosaur',speed:.58,hp:65,dinosaur:true,herbivore:true,tall:true},
  {id:'dinoAnky',name:'Acorazado Anquilosaurio',body:0x6d7257,head:0x81866a,kind:'dinosaur',speed:.55,hp:44,dinosaur:true,herbivore:true,wide:true},
  {id:'dinoPtero',name:'Planeador Pterodáctilo',body:0x98775c,head:0xb08a69,kind:'dinosaur',speed:1.45,hp:18,dinosaur:true,flying:true,carnivore:true},
  {id:'dinoSpino',name:'Espinosaurio acuático',body:0x365859,head:0x497576,kind:'dinosaur',speed:1.2,hp:58,dinosaur:true,carnivore:true,tall:true},
  {id:'dinoDilopho',name:'Dilofosaurio venenoso',body:0x3d7042,head:0xc9493a,kind:'dinosaur',speed:1.4,hp:26,dinosaur:true,carnivore:true},
  {id:'dinoCarnotaur',name:'Carnotauro cornudo',body:0x8a4537,head:0xa85343,kind:'dinosaur',speed:1.55,hp:40,dinosaur:true,carnivore:true},

  // Marvel Zombies Add-on
  {id:'mzBasic',name:'Zombie apocalíptico',body:0x5b7449,head:0x77955f,kind:'hostile',speed:1.05,hp:16,marvelZombie:true},
  {id:'mzSkrull',name:'Zombie Skrull',body:0x566b53,head:0x7da56f,kind:'hostile',speed:1.15,hp:18,marvelZombie:true},
  {id:'mzMummy',name:'Momia infectada',body:0xb8ad91,head:0xd0c4a5,kind:'hostile',speed:.78,hp:22,marvelZombie:true},
  {id:'mzCowboy',name:'Zombie vaquero',body:0x6c5138,head:0x7f9a63,kind:'hostile',speed:1.08,hp:20,marvelZombie:true},
  {id:'mzIron',name:'Zombie Iron Man',body:0x9f2e2d,head:0xc34635,kind:'hostile',speed:1.25,hp:36,marvelZombie:true,superZombie:true},
  {id:'mzCap',name:'Zombie Captain America',body:0x334f79,head:0x66896e,kind:'hostile',speed:1.22,hp:40,marvelZombie:true,superZombie:true},
  {id:'mzWolverine',name:'Zombie Wolverine',body:0x8d792d,head:0x71945a,kind:'hostile',speed:1.55,hp:38,marvelZombie:true,superZombie:true},
  {id:'mzSpider',name:'Zombie Spider-Man',body:0x8c2f38,head:0xa53a45,kind:'hostile',speed:1.65,hp:32,marvelZombie:true,superZombie:true},
  {id:'mzSymbioteSpider',name:'Zombie Spider-Man Simbionte',body:0x151518,head:0x222228,kind:'hostile',speed:1.75,hp:46,marvelZombie:true,superZombie:true},
  {id:'mzCarnage',name:'Zombie Carnage Zarcillos',body:0x9e1212,head:0xc71818,kind:'hostile',speed:1.80,hp:62,marvelZombie:true,superZombie:true,tall:true},
  {id:'mzBlackPanther',name:'Zombie Black Panther',body:0x222226,head:0x33333b,kind:'hostile',speed:1.60,hp:42,marvelZombie:true,superZombie:true},
  {id:'mzHulk',name:'Zombie Hulk',body:0x4f7e43,head:0x6d9e5b,kind:'hostile',speed:1.0,hp:85,marvelZombie:true,superZombie:true,tall:true},
  {id:'mzStrange',name:'Zombie Doctor Strange',body:0x65436e,head:0x789367,kind:'hostile',speed:1.15,hp:50,marvelZombie:true,superZombie:true},
  {id:'mzThanos',name:'Zombie Thanos',body:0x66527d,head:0x7d678e,kind:'hostile',speed:.95,hp:115,marvelZombie:true,superZombie:true,tall:true},
  {id:'mzThor',name:'Zombie Thor el del Trueno',body:0x2c4363,head:0x527299,kind:'hostile',speed:1.25,hp:54,marvelZombie:true,superZombie:true},
  {id:'mzScarlet',name:'Zombie Bruja Escarlata',body:0x7a2228,head:0xa82d36,kind:'hostile',speed:1.18,hp:48,marvelZombie:true,superZombie:true},
  {id:'mzDeadpool',name:'Zombie Deadpool',body:0x8c2626,head:0x1b1b1b,kind:'hostile',speed:1.5,hp:42,marvelZombie:true,superZombie:true},
  {id:'mzVenom',name:'Zombie Venom Simbionte',body:0x141416,head:0x222228,kind:'hostile',speed:1.35,hp:68,marvelZombie:true,superZombie:true,tall:true},
]

export const ITEMS = [
  ...BLOCKS.map((b,blockIndex)=>({name:b.name,category:'Bloques',icon:'■',kind:'block',blockIndex})),
  ...TOOLS.map((t,toolIndex)=>({name:t.name,category:'Herramientas',icon:t.icon,kind:'tool',toolIndex})),
  ...['Palo','Carbón','Lingote de hierro','Lingote de oro','Diamante','Esmeralda','Cobre','Redstone','Cuarzo','Amatista','Pedernal','Cuero','Pluma','Hilo','Hueso','Bola de gel','Pólvora','Papel','Libro','Botella','Cubo','Brújula','Reloj','Mapa vacío','Perla extraña','Polvo brillante'].map(name=>({name,category:'Materiales',icon:'◆',kind:'item'})),
  ...['Manzana','Pan','Zanahoria','Papa','Melón','Bayas','Carne cocida','Pescado','Galleta','Pastel','Sopa de hongos','Miel','Manzana dorada','Carne cruda'].map(name=>({name,category:'Comida',icon:'●',kind:'item'})),
  ...['Fósil sin limpiar','Fragmento de ámbar','ADN incompleto','ADN de dinosaurio','Jeringa de ADN puro','Nutrientes de incubación','Huevo incubado'].map(name=>({name,category:'Paleontología',icon:'◈',kind:'item'})),
  ...[
    ['Vendaje','✚'],['Botiquín','🧰'],['Punto de refugio','⌂'],['Núcleo repulsor','◉'],
    ['Escudo del capitán','◈'],['Lanzatelarañas','✣'],['Lanzatelarañas Simbiótico','🕸️'],['Simbionte Negro puro','🖤'],['Puño gamma','✹'],['Sello místico','✦'],
    ['Guantelete del infinito','✺'],['Suero restaurador','🧪'],['Suero de Súper Soldado','⭐']
  ].map(([name,icon])=>({name,category:'Marvel Zombies',icon,kind:'item',marvelItem:true})),
  ...MOB_TYPES.map((m,mobType)=>({name:`Huevo: ${m.name}`,category:'Criaturas',icon:'◉',kind:'spawnEgg',mobType,eggColor:m.head})),
]

export const CRAFTABLES = [
  {name:'Tablones',ins:[{kind:'block',id:'oak',count:1}],out:{kind:'block',id:'planks',count:4}},
  {name:'Palo',ins:[{kind:'block',id:'planks',count:2}],out:{kind:'item',name:'Palo',count:4}},
  {name:'Papel',ins:[{kind:'block',id:'bamboo',count:1}],out:{kind:'item',name:'Papel',count:3}},
  {name:'Libro',ins:[{kind:'item',name:'Papel',count:3}],out:{kind:'item',name:'Libro',count:1}},
  {name:'Mesa de crafteo',ins:[{kind:'block',id:'planks',count:4}],out:{kind:'block',id:'crafting',count:1}},
  {name:'Horno',ins:[{kind:'block',id:'cobble',count:8}],out:{kind:'block',id:'furnace',count:1}},
  {name:'Cofre',ins:[{kind:'block',id:'planks',count:8}],out:{kind:'block',id:'chest',count:1}},
  {name:'Dinamita TNT',ins:[{kind:'item',name:'Pólvora',count:5},{kind:'block',id:'sand',count:4}],out:{kind:'block',id:'tnt',count:1}},
  {name:'Mesa de encantamientos',ins:[{kind:'item',name:'Libro',count:1},{kind:'block',id:'diamond',count:2},{kind:'block',id:'obsidian',count:4}],out:{kind:'block',id:'enchantTable',count:1}},
  {name:'Manzana dorada',ins:[{kind:'item',name:'Manzana',count:1},{kind:'item',name:'Lingote de oro',count:8}],out:{kind:'item',name:'Manzana dorada',count:1}},
  {name:'Chisquero de pedernal',ins:[{kind:'item',name:'Lingote de hierro',count:1},{kind:'item',name:'Pedernal',count:1}],out:{kind:'tool',name:'Chisquero de pedernal',count:1}},
  {name:'Peto de hierro',ins:[{kind:'item',name:'Lingote de hierro',count:8}],out:{kind:'tool',name:'Peto de hierro',count:1}},
  {name:'Peto de diamante',ins:[{kind:'block',id:'diamond',count:8}],out:{kind:'tool',name:'Peto de diamante',count:1}},
  
  // Jurassic World Crafts
  {name:'Rifle tranquilizante',ins:[{kind:'block',id:'iron',count:3},{kind:'item',name:'Palo',count:2},{kind:'block',id:'redstone',count:1}],out:{kind:'tool',name:'Rifle tranquilizante',count:1}},
  {name:'Rastreador jurásico',ins:[{kind:'block',id:'copper',count:2},{kind:'block',id:'glass',count:1},{kind:'block',id:'redstone',count:1}],out:{kind:'tool',name:'Rastreador jurásico',count:1}},
  {name:'Analizador de ADN',ins:[{kind:'block',id:'iron',count:2},{kind:'block',id:'glass',count:1},{kind:'block',id:'copper',count:1}],out:{kind:'block',id:'dnaAnalyzer',count:1}},
  {name:'Incubadora',ins:[{kind:'block',id:'glass',count:2},{kind:'block',id:'iron',count:1},{kind:'block',id:'copper',count:1}],out:{kind:'block',id:'incubator',count:1}},

  // Marvel Zombies Crafts & Symbiote Spider-Man
  {name:'Traje Simbionte Spider-Man',ins:[{kind:'item',name:'Lanzatelarañas',count:1},{kind:'item',name:'Simbionte Negro puro',count:1}],out:{kind:'tool',name:'Traje Simbionte Spider-Man',count:1}},
  {name:'Simbionte Negro puro',ins:[{kind:'item',name:'Bola de gel',count:2},{kind:'block',id:'blackstone',count:2}],out:{kind:'item',name:'Simbionte Negro puro',count:1}},
  {name:'Lanzatelarañas Simbiótico',ins:[{kind:'item',name:'Hilo',count:4},{kind:'item',name:'Simbionte Negro puro',count:1}],out:{kind:'item',name:'Lanzatelarañas Simbiótico',count:2}},
  {name:'Martillo Mjolnir',ins:[{kind:'block',id:'iron',count:4},{kind:'item',name:'Palo',count:2},{kind:'block',id:'amethyst',count:2}],out:{kind:'tool',name:'Martillo Mjolnir',count:1}},
  {name:'Arco explosivo de Hawkeye',ins:[{kind:'tool',name:'Arco',count:1},{kind:'item',name:'Pólvora',count:3}],out:{kind:'tool',name:'Arco explosivo de Hawkeye',count:1}},
  {name:'Guantelete repulsor',ins:[{kind:'block',id:'iron',count:4},{kind:'block',id:'gold',count:2},{kind:'block',id:'redstone',count:2}],out:{kind:'tool',name:'Guantelete repulsor',count:1}},
  {name:'Suero de Súper Soldado',ins:[{kind:'item',name:'Suero restaurador',count:1},{kind:'item',name:'Manzana dorada',count:1}],out:{kind:'item',name:'Suero de Súper Soldado',count:1}},

  {name:'Vidrio',ins:[{kind:'block',id:'sand',count:2}],out:{kind:'block',id:'glass',count:1}},
  {name:'Ladrillos',ins:[{kind:'block',id:'clay',count:1}],out:{kind:'block',id:'brick',count:1}},
  {name:'Librería',ins:[{kind:'block',id:'planks',count:2},{kind:'item',name:'Libro',count:3}],out:{kind:'block',id:'bookshelf',count:1}},
  {name:'Lámpara',ins:[{kind:'block',id:'glow',count:1},{kind:'block',id:'redstone',count:1}],out:{kind:'block',id:'lamp',count:1}},
  {name:'Cable conductor',ins:[{kind:'block',id:'redstone',count:1},{kind:'block',id:'stone',count:1}],out:{kind:'block',id:'powerDust',count:2}},
  {name:'Palanca',ins:[{kind:'item',name:'Palo',count:1},{kind:'block',id:'cobble',count:1}],out:{kind:'block',id:'lever',count:1}},
  {name:'Lámpara eléctrica',ins:[{kind:'block',id:'glow',count:1},{kind:'block',id:'redstone',count:1},{kind:'block',id:'copper',count:1}],out:{kind:'block',id:'powerLamp',count:1}},
  {name:'Núcleo de portal',ins:[{kind:'block',id:'obsidian',count:2},{kind:'block',id:'amethyst',count:1}],out:{kind:'block',id:'portalCore',count:1}},
  {name:'Pico de madera',ins:[{kind:'block',id:'planks',count:3},{kind:'item',name:'Palo',count:2}],out:{kind:'tool',name:'Pico de madera',count:1}},
  {name:'Pico de piedra',ins:[{kind:'block',id:'cobble',count:3},{kind:'item',name:'Palo',count:2}],out:{kind:'tool',name:'Pico de piedra',count:1}},
  {name:'Pico de hierro',ins:[{kind:'block',id:'iron',count:3},{kind:'item',name:'Palo',count:2}],out:{kind:'tool',name:'Pico de hierro',count:1}},
  {name:'Pico de diamante',ins:[{kind:'block',id:'diamond',count:3},{kind:'item',name:'Palo',count:2}],out:{kind:'tool',name:'Pico de diamante',count:1}},
  {name:'Hacha de madera',ins:[{kind:'block',id:'planks',count:3},{kind:'item',name:'Palo',count:2}],out:{kind:'tool',name:'Hacha de madera',count:1}},
  {name:'Pala de madera',ins:[{kind:'block',id:'planks',count:1},{kind:'item',name:'Palo',count:2}],out:{kind:'tool',name:'Pala de madera',count:1}},
  {name:'Espada de hierro',ins:[{kind:'block',id:'iron',count:2},{kind:'item',name:'Palo',count:1}],out:{kind:'tool',name:'Espada de hierro',count:1}},
  {name:'Espada de diamante',ins:[{kind:'block',id:'diamond',count:2},{kind:'item',name:'Palo',count:1}],out:{kind:'tool',name:'Espada de diamante',count:1}},
  {name:'Arco',ins:[{kind:'item',name:'Palo',count:3},{kind:'item',name:'Hilo',count:3}],out:{kind:'tool',name:'Arco',count:1}},
  {name:'Escudo',ins:[{kind:'block',id:'iron',count:1},{kind:'block',id:'planks',count:6}],out:{kind:'tool',name:'Escudo',count:1}},
  {name:'Muro reforzado',ins:[{kind:'block',id:'iron',count:2},{kind:'block',id:'stone',count:4}],out:{kind:'block',id:'reinforcedWall',count:4}},
  {name:'Cristal antizombies',ins:[{kind:'block',id:'glass',count:2},{kind:'block',id:'iron',count:1}],out:{kind:'block',id:'antiZombieGlass',count:2}},
  {name:'Cerca eléctrica',ins:[{kind:'block',id:'iron',count:2},{kind:'block',id:'powerDust',count:1}],out:{kind:'block',id:'electricFence',count:3}},
  {name:'Radar Mini-IA',ins:[{kind:'block',id:'iron',count:3},{kind:'block',id:'copper',count:2},{kind:'block',id:'redstone',count:2}],out:{kind:'block',id:'radarArray',count:1}},
  {name:'Escáner biológico',ins:[{kind:'block',id:'glass',count:1},{kind:'block',id:'copper',count:2},{kind:'block',id:'redstone',count:1}],out:{kind:'block',id:'bioScanner',count:1}},
  {name:'Estación médica',ins:[{kind:'block',id:'iron',count:2},{kind:'block',id:'glass',count:2},{kind:'block',id:'seaLantern',count:1}],out:{kind:'block',id:'medicalStation',count:1}},
  {name:'Llave de ingeniería',ins:[{kind:'block',id:'iron',count:2},{kind:'item',name:'Palo',count:1}],out:{kind:'tool',name:'Llave de ingeniería',count:1}},
  {name:'Bastón eléctrico',ins:[{kind:'block',id:'copper',count:2},{kind:'block',id:'powerDust',count:1},{kind:'item',name:'Palo',count:1}],out:{kind:'tool',name:'Bastón eléctrico',count:1}},
  {name:'Brocha paleontológica',ins:[{kind:'item',name:'Palo',count:1},{kind:'item',name:'Pluma',count:2}],out:{kind:'tool',name:'Brocha paleontológica',count:1}},
  {name:'Suero restaurador',ins:[{kind:'item',name:'Botiquín',count:1},{kind:'item',name:'Botella',count:1},{kind:'item',name:'Polvo brillante',count:1}],out:{kind:'item',name:'Suero restaurador',count:1}},
]
